name: 'Check Egress Rules'
description: 'Validates if egress rules exist'
inputs:
  map:
    description: 'Host and ports map'
    required: true
  environment:
    description: 'Environment name'
    required: true
  token:
    description: 'Auth token for API'
    required: true
outputs:
  status:
    description: 'Result of egress check'
runs:
  using: 'node16'
  main: 'index.js'
